### ISSUE TITLE
Incorrect printing when function call inside?

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#15] opened 2016-02-09 15:10 UTC
As of https://github.com/rafalcieslak/CCoscope/commit/e34675e86e395343663e4ee14fa2488bd7612ac7 , when we look at the LLVM's IR our compiler produces on `examples/pow.cco`, we get

```
@0 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@1 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@2 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@3 = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@4 = private unnamed_addr constant [4 x i8] c"%d\0A\00"

declare i32 @putchar(i32)

declare i32 @printf(i8*, ...)

declare double @pow(double, double)

define i32 @main() {
entry:
  %c_addr = alloca double
  %b_addr = alloca double
  %a_addr = alloca double
  store double 0.000000e+00, double* %a_addr
  store double 0.000000e+00, double* %b_addr
  store double 0.000000e+00, double* %c_addr
  store double 3.000000e+00, double* %a_addr
  store double 2.000000e+00, double* %b_addr
  %a = load double, double* %a_addr
  %b = load double, double* %b_addr
  %calltmp = call double @pow(double %a, double %b)
  store double %calltmp, double* %c_addr
  %a1 = load double, double* %a_addr
  %calltmp2 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @0, i32 0, i32 0), double %a1)
  %b3 = load double, double* %b_addr
  %calltmp4 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @1, i32 0, i32 0), double %b3)
  %c = load double, double* %c_addr
  %calltmp5 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @2, i32 0, i32 0), double %c)
  %a6 = load double, double* %a_addr
  %b7 = load double, double* %b_addr
  %calltmp8 = call double @pow(double %a6, double %b7)
  %calltmp9 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @3, i32 0, i32 0), double %calltmp8)
  %calltmp10 = call double @pow(double 3.000000e+00, double 2.000000e+00)
  %calltmp11 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @4, i32 0, i32 0), double %calltmp10)
  ret i32 0
}
```

The problem is that the last two calls to `printf` get the `%d` format specifier, and as a result those calls print rubbish. This must probably be the issue involving `maintype` member function in AST class -- which is basically stubbed out, but I believe it should produce correct results in current state of implementation. The ad-hoc solution in `CallExprAST::codegen` doesn't work unfortunately.

As a side note -- how about throwing away all of our type enums and type classes and use type system that LLVM provides? It should be safer and maybe problems will magically disappear.

**Comment by rafalcieslak** [comment] 2016-02-09 15:34
No, I believe the problem is slightly somewhere else.

First, I am strongly against using llvm values' types for our internal processing.
- If we do, we limit ourselves only to types that can be represented as llvm simple types, and if at some point in the future we decide we would like to have arrays or strings or custom types, we'll need to re-implement all of it. Also it will be very difficult to even slightly digress from a C-like language if we strictly use only LLVM types.
- We already need some types that llvm does not provide, namely a void.
- LLVM does not provide a type system, it just keeps track of how a simple value would be represented at machine-level. Our AST does not work at machine-level, and we have the freedom to have it represent high-level types. LLVM won't help us by telling whether type A is convertible to B, we need to determine that on our own anyway.
- Keeping track of how a value is represented at machine-level will not be enough for complex types, as they will all be just pointers.

So we really can't rely on LLVM tracking types for us.

The way I see it is that instead of working on `llvm::Value`s (which are a returned by `codegen`s) we should actually work on `TypedValue`s:

```
struct TypedValue{
    llvm::Value llvmval;
    datatype type;
}
```

so that we have both a llvm low-level register value, as well as an information how we should interpret this value (think complex types).

What I find potentially problematic in the current code is the `maintype` method. Are we really interested in "what is the typical value type this type of statement returns"? I think what we need is "what is the actual value type returned by this particular statement". Clearly, when printing a value of a call, the call may return various types, depending on what function it calls. So the print statement won't be interested in "what calls generally return", but in "what this particular call returns". The same point works for expression statements, which may return different types depending on their argument.

If we used TypedValues, then instead of llvm:Values, then we could never call `maintype`, and just perform the `codegen` instead, and see it's returned type - which will be always the correct one, even if any overloads are resolved during code generation.

**Comment by rafalcieslak** [comment] 2016-02-09 15:35
I see it took you less time to workaround this issue, then me to write up the above. Reopening the issue as the discussion is not finished, and I don't really like the current solution.

**Comment by socumbersome** [comment] 2016-02-09 19:34
To address your points: as far as I can see LLVM has void type (`Type::getVoidTy()`), it has struct types, vector types and there is some API for conversions (http://llvm.org/docs/doxygen/html/classllvm_1_1CastInst.html), but I agree with you that having our own type system is better (as long as `datatype` is not an enum, I think). 

And maybe even having own types and a method `toLLVMType` would be even better (once calculated, could be cached, but I'm not convinced about having `TypedValue` struct floating around).

Also, having looked around the code, I see that sometimes we convert the other way round. I don't know whether this is necessary and whether there is some workaround to not have to do this, but if we need to have two-way relation, then it might be painful (being able to convert every LLVM's type into our type system).

As to the "what this particular call returns" thing -- sorry, I don't understand. Every instance of `CallExprAST` can return different type, because the return type is determined by the Callee. I think that's reasonable?

And as to getting rid of `maintype` and having `codegen` only -- it might badly affect our future work. I cannot foresee every problem, but won't "real" typechecking become a must when our language will grow (strings, temporaries etc.)?

As a side note: Is there a way to move (as in move semantics :)) your comment with concerns and this one to a new issue and close this one? The truth is that printing is now correct so, technically, the issue should be closed :)

**Comment by rafalcieslak** [comment] 2016-02-09 20:02
Github's issue management is very limited, and there is no way to detach some comments from an issue and attach them somewhere else...

The potential problem that I see is that the mapping from out types to LLVM types may not be injective, and therefore an inverse function may not exist. In such case we would be forced to somehow tag LLVM values with our types, as the value itself will not contain enough information.

Could you please point me to the places where we actually convert from LLVM type to "our type"? As far as I see all these cases are just temporary workarounds. For example, [have a look at this "conversion"](https://github.com/rafalcieslak/CCoscope/blob/044f5f8e55a53adbb33e716a7cf79a9e008c0b86/src/tree.cpp#L549). Such trick is needed only because we are not (yet) storing information about function return types. If we did, then instead of searching for the function in the module and retrieving it's low-level type, we would lookup the function in the function storage, and the actual high-level returned type for it would be there. We will need such storage for function prototypes anyway, beause one day function won't have to return a `float` or an `int`, but they will also return `string`s, `foo`s and `bar`s, but because these are all complex types, these functions will actually return a `void *` (or even a void, because it may return the result as a reference implicitly passed as argument, see lecture 14), and we will not be able to tell, given a function from a module, whether that `void *` it returns is a `foo` or a `bar`.

Part of my confusion about `maintype`s was because at the time I have last seen the implementation, the `maintype` for `CallExprAST` would simply return a void, which I found very weird, because each function may return a different value. The idea is clearer to me now, though I find the name `maintype` misleading. Also, in that case, we need to implement `maintype` for `BinaryExprAST`, as otherwise `print(2+2)` won't work, since apparently the type of `2+2` is void. Note that operator overloading would have to be resolved in `maintype` as well as in `codegen`, so it will be probably a good moment to extract common code.

Let's have a look at another [piece of code that extracts types from LLVM](https://github.com/rafalcieslak/CCoscope/blob/044f5f8e55a53adbb33e716a7cf79a9e008c0b86/src/tree.cpp#L108). Again, I believe that is unnecessary, and it's just a temporary solution. In this context the types of sub-expressions are needed in order to perform correct overload resolution. So in order to get these types, we let both subexpressions `codegen` themselves, and we look at their returned LLVM values, and check their types, to convert it to higher-level types. Fine, but since we have both subexpressions anyway, why won't we just ask them to determine their "high-level" type? As far as I understand, this is exactly what `maintype` does (except it is currently broken for `BinaryExprAST`), so let's use it to get the real types of both values.

As far as I see, there are no other cases of extracting types from LLVM, and I can't really imagine a situation where that would be unavoidable. Sure, it's easy and simple, but very limiting.

Also, by the way, what are these constant values in `maintype`, and why are significant? Do we need that 42? Shoudn't `maintype` return just a datatype?

**Comment by socumbersome** [comment] 2016-02-10 18:21
Let me just answer briefly because, overall, I agree with you.

Initially, I thought that doing double bookkeeping with storing functions wouldn't be nice but the point about easily retrieving "our" type mitigates it.

As to the return type of `maintype` -- whether we need the first component (that is another `AST` node) or not depends on our approach:
1) if we model type conversions, temporary values, implicit loads etc. as "real" `AST` things, then `maintype` is allowed to change the thing it is typechecking by inserting such nodes -- but because mutable state is barbaric, we return newly created thing :) Then codegenning is easier and more elegant, I think, because there will be no (or not much of) type-gymnastics involved
2) we allow for `codegen` to play with type conversions and stuff, but then typechecking itself would probably become both weaker (we don't check as much as in 1)) and more complicated (less information means more struggling to make types fit to one another properly)

I'd opt for the 1) option. The difficulty it poses is that we need a clever way to keep track of the "most up-to-date" AST objects (i.e. not refer to `A` if `A.maintype` returned `<B, t>`, but use `B` from now on). I have an idea of having representatives, so that, initially, `A.representative = A`, but then `A.representative = B` and hide all of such chains under a lightweight proxy `P`, so that we always use `P` and, underneath, it retrieves `A` or `B` when asked for AST objects.
I hope that makes sense :)

Anyway, I'll try to adjust everything to work on `CCType`s from `typechecking.h` (which probably should be called `types.h`).

**Closed as completed** 2016-02-14 20:59 UTC
Labels: bug, question
